spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testserver?serverTimezone=UTC&useSSL=false&allowMultiQueries=true
      username: root
      password: root